version: '3.5'

networks:
  floppaland-net:
    external:
      name: main-net

services:
  launchserver:
    image: ijo42/glauncher:latest
        
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 9274:9274
    volumes:
      - /home/server/launcher:/app/launchserver
    environment:
      - TZ=Europe/Moscow # Timezone
      - PUID=1000  # User  ID `id $(whoami) -u`
      - PGID=1000  # Group ID `id $(whoami) -g`
    networks:
      - floppaland-net

  kubek:
    image: seeroy/kubek-minecraft-dashboard
    restart: always
    ports:
      - 3000:3000
      - 25565:25565
    volumes:
      - /home/server/kubek-servs:/usr/kubek/servers
      #- .kubek-servs/config.json:/usr/kubek/config.json
    networks:
      - floppaland-net
    depends_on:
      launchserver:
        condition: service_started
    

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /home/server/postgres-data:/var/lib/postgresql/data
    networks:
      - floppaland-net
      
  adminer:
    image: adminer
    restart: always
    #ports:
      # - 8088:8080

  flask_web:
    build: ./site/
    ports:
      - 5000:5000
    volumes:
      - /home/server/site/:/app
    networks:
      - floppaland-net
    depends_on:
      - db

#  nginx:
#    image: nginx
#    volumes:
#    - /home/server/:/var/www/app/public/
#    - /home/server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#    - "80:80"
#    environment:
#    - NGINX_HOST=floppaland.com
#    - NGINX_PORT=80 
#    depends_on:
#      flask_web:
#        condition: service_started
#      adminer:
#        condition: service_started
#      launchserver:
#        condition: service_started
#      kubek:
#        condition: service_started
